# Generated by Django 2.2.3 on 2020-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasmarket', '0002_auto_20200303_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
    ]
