# Generated by Django 2.2.3 on 2020-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasmarket', '0007_listing_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
    ]
