# Generated by Django 2.2.3 on 2020-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasmarket', '0009_auto_20200305_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
