# Generated by Django 2.2.3 on 2020-03-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glasmarket', '0015_auto_20200306_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
