# Generated by Django 2.2.3 on 2020-03-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasmarket', '0022_auto_20200310_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(default=0, upload_to='listings_images'),
        ),
    ]
