# Generated by Django 2.2.3 on 2020-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasmarket', '0025_auto_20200311_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, default=0, upload_to='listings_images'),
        ),
    ]
